server: 
 port: 8090 

logging: 
  config: classpath:log4j2.xml
  
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.domain
  mapperLocations: classpath:mapper/*.xml